#!/bin/bash

#	link to Makefile:
makefileurl="https://webcourse.cs.technion.ac.il/fc159753hw_236360_202001/hw/WCFiles/makefile"
#	link to tests:
testsurl="https://webcourse.cs.technion.ac.il/fc159753hw_236360_202001/hw/WCFiles/hw5-tests.zip"
#	number of tests:
numtests=3

hostname="cscomp"
tmpdir="selfcheck_tmp"

if [ $( hostname ) != "$hostname" ]
then
  echo "This script is only intended to run on "$hostname"!"
  exit
fi



rm -rf "$tmpdir" &> /dev/null
if [ -d "$tmpdir" ]
then
  echo "Cannot clear tmp directory. Please delete '"$tmpdir"' manually and try again"
  exit
fi
mkdir "$tmpdir" &> /dev/null


make &> /dev/null

cp hw5 ${tmpdir}/

if [[ ! -f "hw5-tests.zip" ]]; then
  wget --no-check-certificate "$testsurl" &> /dev/null
fi

if [ ! -f $( basename "$testsurl" ) ]
then
  echo "Unable to download tests!"
  exit
fi

unzip $( basename "$testsurl" ) -d ${tmpdir}/
if [[ $? != 0 ]]
then
  echo "Unable to unzip tests!"
  exit
fi

cd "$tmpdir"


i="1"
while [ $i -le $numtests ]
do
  ./hw5 < t$i.in 2>&1 > t$i.ll
  echo "Hello Mufasa"
  lli t$i.ll > t$i.res
  echo "GoodBye Mufasa"
  diff t$i.res t$i.out &> /dev/null
  if [[ $? != 0 ]]
  then
      diff -y t$i.res t$i.out
    echo "Failed test #"$i"!"
    exit
  fi
  i=$[$i+1]
done

cd - &> /dev/null
# rm -rf "$tmpdir"

echo "Ok to submit :)"
exit
