#!/bin/bash

function checks(){
	if [$1 -eq 1]; then
		if [ $( hostname ) != "$hostname" ]
		then
			echo "This script is only intended to run on "$hostname"!"
			exit
		fi

		if [ -z "$1" ]
		then
			echo "Usage: ./"$( basename "$0" )" <your submission zip file>"
			exit
		fi

		if [ ! -f "$1" ]
		then
			echo "Submission zip file not found!"
			exit
		fi
	fi
	if [$1 -eq 2]; then
		if [ -d "$tmpdir" ]
		then
			echo "Cannot clear tmp directory. Please delete '"$tmpdir"' manually and try again"
			exit
		fi
	fi
	if [$1 -eq 3]; then
		if [[ $? != 0 ]]
		then
			echo "Unable to unzip submission file!"
			exit
		fi
	fi

	if [$1 -eq 4]; then
		if [ ! -f scanner.lex ]
		then
			echo "File scanner.lex not found!"
			exit
		fi

		if [ ! -f parser.ypp ]
		then
			echo "File parser.ypp not found!"
			exit
		fi
	fi

	if [$1 -eq 5]; then
		if [ ! -f makefile ]
		then
			echo "Unable to download makefile!"
			exit
		fi
	fi

	if [$1 -eq 6]; then
		if [[ $? != 0 ]]
		then
			echo "Cannot build submission!"
			exit
		fi
	fi

	if [$1 -eq 7]; then
		if [ ! -f $( basename "$testsurl" ) ]
		then
			echo "Unable to download tests!"
			exit
		fi
	fi

	if [$1 -eq 8]; then
		if [[ $? != 0 ]]
		then
			echo "Unable to unzip tests!"
			exit
		fi
	fi
}


#	link to Makefile:
makefileurl="https://webcourse.cs.technion.ac.il/fc159753hw_236360_201901/hw/WCFiles/makefile"
#	link to tests:
testsurl="https://webcourse.cs.technion.ac.il/fc159753hw_236360_201901/hw/WCFiles/hw5-tests.zip"
#	number of tests:
numtests=3

hostname="cscomp"
tmpdir="selfcheck_tmp"

checks 1
rm -rf "$tmpdir" &> /dev/null
checks 2
mkdir "$tmpdir" &> /dev/null
unzip "$1" -d "$tmpdir" &> /dev/null
checks 3
cd "$tmpdir"
checks 4
wget --no-check-certificate "$makefileurl" &> /dev/null
checks 5
make &> /dev/null
checks 6
wget --no-check-certificate "$testsurl" &> /dev/null
checks 7
unzip $( basename "$testsurl" ) &> /dev/null
checks 8


i="1"
while [ $i -le $numtests ]
do
	./hw5 < t$i.in 2>&1 > t$i.ll
	lli t$i.ll > t$i.res
	diff t$i.res t$i.out &> /dev/null
	if [[ $? != 0 ]]
	then
		echo "Failed test #"$i"!"
		exit
	fi
	i=$[$i+1]
done

cd - &> /dev/null
rm -rf "$tmpdir"

echo "Ok to submit :)"
exit
